MusicStoreWeb/Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using MusicStore.Domain.Abstract;
using MusicStore.Domain.Entities;
using MusicStore.Domain.Models;
using MusicStoreWeb.Models;

namespace MusicStoreWeb.Controllers
{
    public class CartController : Controller
    {
        private ISongsRepository repository;
        private IOrderItemRepository orderItemRepository;
        private IOrderProcessor orderProcessor;
        private IShippingDetailRepository shippingDetailRepository;
        private IOrderRepository OrderRepository;
        private IUserRepository UserRepository;
        public CartController(ISongsRepository repo, IOrderProcessor proc, IShippingDetailRepository sdetail, IOrderRepository orderRepository, IUserRepository userRepository, IOrderItemRepository orderItemRepository)
        {
            repository = repo;
            orderProcessor = proc;
            shippingDetailRepository = sdetail;
            OrderRepository = orderRepository;
            UserRepository = userRepository;
            this.orderItemRepository = orderItemRepository;
        }
        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                ReturnUrl = returnUrl,
                Cart = cart
            });
        }
        public RedirectToRouteResult AddToCart(Cart cart, int ID, string returnUrl)
        {
            Songs product = repository.Songs
            .FirstOrDefault(p => p.ID == ID);
            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }


        [HttpPost]
        public ActionResult RemoveFromCart(Cart cart, int ID, string returnUrl)
        {
            Songs product = repository.Songs
            .FirstOrDefault(p => p.ID == ID);
            if (product != null)
            {
                cart.RemoveLine(product);
            }

            CartIndexViewModel model = new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            };
            return PartialView("Recipt", model);
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        public ViewResult Checkout(Cart cart)
        {

            string value = "";

            if (Request.Cookies["fatcookie"] != null)
            {
                string value2 = Request.Cookies["fatcookie"]["username"];
                value = value2;

            }

            var user = UserRepository.User
            .Where(p => p.Username == value).FirstOrDefault();

            int ID = user.ID;


            ShippingDetail detail = shippingDetailRepository.ShippingDetail
           .LastOrDefault(p => p.ID == ID);
           

            CartIndexViewModel indexView = new CartIndexViewModel
            {
                shippingDetails = detail,
                Cart = cart
            };


            if (detail != null)
            {
                return View("FinalStep", indexView);
            }

            else
            {
                return View(new ShippingDetail());
            }
        }
        public ViewResult newShippingDetails(ShippingDetail detail)
        {
            string value = "";

            if (Request.Cookies["fatcookie"] != null)
            {
                string value2 = Request.Cookies["fatcookie"]["username"];
                value = value2;

            }

            var user = UserRepository.User
            .Where(p => p.Username == value).FirstOrDefault();

            int ID = user.ID;


            if (ModelState.IsValid)
            {


                shippingDetailRepository.SaveShippingDeatails(detail);

            }

            return View("Checkout");
            
          
        }
        public ViewResult editShipping()
        {


            string value = "";

            if (Request.Cookies["fatcookie"] != null)
            {
                string value2 = Request.Cookies["fatcookie"]["username"];
                value = value2;

            }

            var user = UserRepository.User
            .Where(p => p.Username == value).FirstOrDefault();

            string name = user.Username;


            ShippingDetail detail = shippingDetailRepository.ShippingDetail.LastOrDefault(p => p.Name== name);

            

            return View("Checkout", detail);
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetail detail)
        {


            string value = "";

            if (Request.Cookies["fatcookie"] != null)
            {
                string value2 = Request.Cookies["fatcookie"]["username"];
                value = value2;

            }


            CartIndexViewModel indexView = new CartIndexViewModel
            {
                shippingDetails = detail,
                Cart = cart
            };


            if (detail != null && ModelState.IsValid)
            {
                shippingDetailRepository.SaveShippingDeatails(detail);
                return View("FinalStep", indexView);
            }

            else
            {
                return View(new ShippingDetail());
            }


        }

        public ActionResult SaveShippingDetails(Cart cart, ShippingDetail shippingDetails)
        {
            


            string value = "";

            if (Request.Cookies["fatcookie"] != null)
            {
                string value2 = Request.Cookies["fatcookie"]["username"];
                value = value2;

            }

            var user = UserRepository.User
            .Where(p => p.Username == value).FirstOrDefault();

            int ID = user.ID;




            ShippingDetail detail = shippingDetailRepository.ShippingDetail
           .LastOrDefault(p => p.ID == ID);

            if (detail == null)
            {
                detail = shippingDetails;
            }

            CartIndexViewModel indexView = new CartIndexViewModel
            {
                shippingDetails = detail,
                Cart = cart
            };

            if (ModelState.IsValid)
            {


                shippingDetailRepository.SaveShippingDeatails(detail);

                TempData["message"] = string.Format("Shipping details with id {0} has been saved", detail.ID);
                return RedirectToAction("Index");
            }
            else
            {
                return View("FinalStep", indexView);
            }
        }



        public ActionResult Finalise(Cart cart)
        {

            

            string value = "";
            
            if (Request.Cookies["fatcookie"] != null)
            {
                string value2 = Request.Cookies["fatcookie"]["username"];
                value = value2;

            }


            var user = UserRepository.User
            .Where(p => p.Username == value).FirstOrDefault();

            var shiping = shippingDetailRepository.ShippingDetail.Where(p => p.Name == value).LastOrDefault();
            int SID = shiping.ID;

            int UID = user.ID;

            CartViewModel model = new CartViewModel
            {
                Cart = cart,
                shippingDetails = shiping

            };

          
            OrderRepository.CreateNewOrder(SID, UID, model);

            Order neworder = OrderRepository.Order.LastOrDefault(p => p.UserID == UID);

            orderItemRepository.AddOrder(neworder.ID, model);

            

            return View("Finalised");
        }
        public ActionResult detailExists(Cart cart)
        {
            string value = "";

            if (Request.Cookies["fatcookie"] != null)
            {
                string value2 = Request.Cookies["fatcookie"]["username"];
                value = value2;

            }

            var userd = shippingDetailRepository.ShippingDetail.Where(m => m.Name == value).FirstOrDefault(); ;

            CartIndexViewModel indexView = new CartIndexViewModel
            {
                shippingDetails = userd,
                Cart = cart
            };

            var s = cart.Lines.FirstOrDefault();


            if (s == null)
            {
                return RedirectToAction("Index");
            }
            else { 
            if (userd== null)
            {
                return RedirectToAction("newShippingDetails", new ShippingDetail());
              
            }
            else
            {

                return View("FinalStep", indexView);
            }
            }


        }

        public ActionResult OrderSongs(Cart cart)
        {


            return View();
        }

    }
}

MusicStoreWeb/Controllers/NavController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using MusicStore.Domain.Abstract;
using System.Linq;
using MusicStore.Domain.Entities;
using MusicStore.Domain.Concrete;
using MusicStoreWeb.Models;

namespace MusicStoreWeb.Controllers
{
    public class NavController : Controller
    {
        private ISongsRepository songsRepository;
        private IGenresRepository genresRepository;



        public NavController(ISongsRepository SongRepo, IGenresRepository GenresRepo)
        {
            songsRepository = SongRepo;
            genresRepository = GenresRepo;
        }
        public PartialViewResult Menu(string category = null)
        {
            
            ViewBag.SelectedCategory = category;

            List<GenreMenuItemModel> categories = genresRepository.Genres
           .Select(x => new GenreMenuItemModel()
           {
               Id = x.ID,
               Name = x.Name
           })
           .OrderBy(x => x.Name).ToList();

                return PartialView("FlexMenu", categories);

        }
    }
}

MusicStoreWeb/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicStore.Domain.Entities;
using MusicStore.Domain.Abstract;
using MusicStore.Domain.Models;
using MusicStoreWeb.Models;
using System.Web.UI;

namespace MusicStoreWeb.Controllers
{
    public class UserController : Controller
    {

       IUserRepository userRepository;
        ISongsRepository songsRepository;
        public UserController(IUserRepository userRepo, ISongsRepository songsRepository)
        {
            userRepository = userRepo;
            this.songsRepository = songsRepository;
        }

        public ActionResult UserSignup()
        {
            return View();
        }
        public ActionResult UserLogin()
        {
            return View();
        }

        public ActionResult Login(User users)
        {
            string username = users.Username;
            string passwrd = users.Password;

            var user = userRepository.User
              .Where(p => p.Username == username && p.Password == passwrd).FirstOrDefault();
            if (user!=null)
            {

            
            int rid = user.RoleID;

            if (rid==1)
            {
               
                TempData["message"] = string.Format("Welcome {0}", user.Username);

                HttpCookie UserCookie = new HttpCookie("fatcookie");
                UserCookie.Values.Add("username", user.Username.ToString());
                UserCookie.Values.Add("ID", user.ID.ToString());
                UserCookie.Values.Add("RID", user.RoleID.ToString());
                   

                    UserCookie.Expires.AddHours(3);

                HttpContext.Response.SetCookie(UserCookie);
                return Redirect(Url.Action("Index", "Admin", user));
            }
            else
            { 
                
                HttpCookie UserCookie = new HttpCookie("fatcookie");
                UserCookie.Values.Add("username", user.Username.ToString());
                UserCookie.Values.Add("ID", user.ID.ToString());
                UserCookie.Expires.AddHours(3);

                HttpContext.Response.SetCookie(UserCookie);
                return Redirect(Url.Action("List", "Music", user));
                
            }
            }
            else { return Redirect(Url.Action("List", "Music")); }
        }

        HttpCookie UserCookie;

        public ActionResult Register(User user)
        {
            List<string> usernames = userRepository.GetUser();
            bool nonRepeated = true;
            foreach (string p in usernames)
            {
                if(p == user.Username)
                {
                    nonRepeated = false;
                }
            }

            if (nonRepeated)
            {
                userRepository.SaveUser(user);

                HttpCookie UserCookie = new HttpCookie("fatcookie");
                UserCookie.Values.Add("username", user.Username.ToString());
                UserCookie.Values.Add("ID", user.ID.ToString());
                UserCookie.Expires.AddHours(3);

                HttpContext.Response.SetCookie(UserCookie);
            }
            else
            {
                //alert showing that the username already exists
            }
          




            return Redirect(Url.Action("List", "Music", new { }));
        }
        public ActionResult Logout(Cart cart)
        {
            if (Request.Cookies["fatcookie"] != null)
            {
                Response.Cookies["fatcookie"].Expires = DateTime.Now.AddDays(-1);
            }
           
            if (cart != null) {

                try
                {
                    foreach (var s in cart.Lines)
                    {


                        int ID = s.Product.ID;
                        Songs product = songsRepository.Songs
                        .FirstOrDefault(p => p.ID == ID);
                        if (product != null)
                        {
                            cart.RemoveLine(product);
                        }


                    }
                }
                catch
                {

                }
               
            
            
            }
           


            return Redirect(Url.Action("List", "Music", new { }));
        }

    }

}

MusicStoreWeb/Views/Shared/ProductSummary.cshtml
@model MusicStore.Domain.Entities.Songs
@using MusicStore.Domain.Entities;
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet"
          type="text/css" />
</head>

<ul id="album-list">

    <div class="well">
        @if (Model.ImageData != null)
        {
            <div class="pull-left" style="margin-right: 10px">
                <img class="img-thumbnail" width="75" height="75"
                     src="@Url.Action("GetImage", "Music", new { Model.ID })" />
            </div>
        }
        else
        {

            <img alt="@Model.Name" src="/Content/Images/placeholder.gif" />
        }
        <h3>
            <strong>@Model.Name</strong>
            <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
        </h3>
        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            <div class="pull-right">
                @Html.HiddenFor(x => x.ID)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="Add to cart" />
            </div>
        }
        <span class="lead"> @Model.Author</span>
    </div>
    </ul>

MusicStoreWeb/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

MusicStoreWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using System.Web.Optimization
<html>
<head>
    <meta charset="utf-8" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")"
          rel="stylesheet" type="text/css" />
   
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")"
            type="text/javascript"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery-3.6.1.min.js"></script>



    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        .navbar-right {
            float: right !important;
            margin-right: 15px;
            margin-left: 15px;
        }
    </style>
</head>
@{ string value = "";
    string rid = "";
    if (Request.Cookies["fatcookie"] != null)
    {
        string r= Request.Cookies["fatcookie"]["RID"];
        rid = r;
        string value2 = Request.Cookies["fatcookie"]["username"];
        value = "Signed as  " + value2;

    }
}
<body>

    <div id="header">



        <h1>
            MUSIC STORE
        </h1>
        <ul id="navlist">

            <li class="top"><h3>@value</h3></li>


            <li class="first">
                <a href="/"
                   id="current">Home</a>
            </li>


            <li>

                @{


                    if (rid == "1")
                    {
                        <a href="https://localhost:44315/Admin/Index">Admin</a>
                        @Html.ActionLink("Logout", "Logout", "User")
                    }
                    else if (value == "")
                    {
                        <a href="https://localhost:44315/User/UserLogin"><img src="~/Content/Img/img_454474.png" height="25" /> </a>




                    }
                    else
                    {
                        <a href="/Cart/Index">Cart</a>

                        @Html.ActionLink("Logout", "Logout", "User")
                    }
                }



            </li>
            </ul>

        <button<a href="/Cart/Index"></a></button>
    </div>

    <!--
    <div id="header">
        <div id="header" role="navigation">
            <a id="header" href="#">
                <span class="hidden-xs">Music Store</span>
                <div class="visible-xs">Music</div>
                <div class="visible-xs">Store</div>
            </a>
            @Html.Action("Summary", "Cart")
        </div>
    </div>
    -->


    <div class="visible-xs">
        @Html.Action("Menu", "Nav", new { horizontalLayout = true })
    </div>
    <div class="row panel">
        <div class="col-sm-3 hidden-xs">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-12 col-sm-8">
            @RenderBody()
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>