MusicStoreWeb/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicStore.Domain.Abstract;
using MusicStore.Domain.Entities;
using MusicStore.Domain.Models;

namespace MusicStoreWeb.Controllers
{
  //  [Authorize]
    public class AdminController : Controller
    {
        private ISongsRepository repository;
        private IGenresRepository genresRepository;
        public AdminController(ISongsRepository SongRepo, IGenresRepository GenresRepo)
        {
            repository = SongRepo;
            genresRepository = GenresRepo;
        }
        public ViewResult Index()
        {
            return View(repository.Songs);
        }
        public ViewResult Edit(int? ID)
        {
            Songs song = repository.Songs
            .FirstOrDefault(p => p.ID == ID);
            SongViewModel model = new SongViewModel();
            if(song != null)
            {
                model.ID=song.ID;
                model.Name = song.Name;
                model.Author= song.Author;
                model.Price= song.Price;
                model.GenreID= song.GenreID;
                model.Length= song.Length;
                model.ImageMimeType= song.ImageMimeType;
                model.ImageData= song.ImageData;
                model.Genres = genresRepository.Genres.Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.ID.ToString()
                }).OrderBy(c => c.Text).ToList();
            }

           



 // genresRepository.Genres.Select(c => new SelectListItem
 // {
 //     Text = c.Name,
 //     Value = c.ID.ToString()
 // }).OrderBy(c => c.Text).ToList(),
 //"Value", "Text")
 //);



            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(SongViewModel product, HttpPostedFileBase image = null)
        {
            {
                if (ModelState.IsValid)
                {
                    if (image != null)
                    {
                        product.ImageMimeType = image.ContentType;
                        product.ImageData = new byte[image.ContentLength];
                        image.InputStream.Read(product.ImageData, 0, image.ContentLength);
                    }

                    repository.SaveProduct(product);
                    TempData["message"] = string.Format("{0} has been saved", product.Name);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(product);
                }
            }
        }

        public ActionResult SaveGenre(Genres product)
        {

                if (ModelState.IsValid)
                {

                genresRepository.SaveGenre(product);
                    TempData["message"] = string.Format("{0} has been saved", product.Name);
                    return RedirectToAction("Index");
                }
                else
                {


                    return View(product);

                }

            
        }

        public ViewResult EditG(int? ID)
        {
            Genres genres = genresRepository.Genres
            .FirstOrDefault(p => p.ID == ID);
            
            return View("SaveGenre",genres);
        }



        public ViewResult Create()
        {
            SongViewModel model = new SongViewModel();
            model.Genres = genresRepository.Genres.Select(c => new SelectListItem
            {
                Text = c.Name,
                Value = c.ID.ToString()
            }).OrderBy(c => c.Text).ToList();

            return View("Edit", model);
        }
        public ViewResult CreateG()
        {
            return View("SaveGenre", new Genres());
        }



        public ViewResult ListGenres()
        {
            return View(genresRepository.Genres);
        }

        [HttpPost]
        public ActionResult Delete(int ID)
        {
            Songs deletedProduct = repository.DeleteProduct(ID);
            if (deletedProduct != null)
            {
                TempData["message"] = string.Format("{0} was deleted",
                deletedProduct.Name);
            }
            return RedirectToAction("Index");
        }

        public ActionResult DeleteG(int ID)
        {
            Genres deletedProduct = genresRepository.DeleteGenre(ID);
            if (deletedProduct != null)
            {
                TempData["message"] = string.Format("{0} was deleted",
                deletedProduct.Name);
            }
            return RedirectToAction("Index");
        }
    }
    public class Genree
    {
        public Genrees Genrees { get; set; }
    }

    public enum Genrees
    {
        Pop,
        Rock
    }
}

MusicStoreWeb/Controllers/MusicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicStore.Domain.Abstract;
using MusicStore.Domain.Entities;
using MusicStoreWeb.Models;

namespace SportsStore.WebUI.Controllers
{
    public class MusicController : Controller
    {
        private ISongsRepository repository;
        private IGenresRepository genresRepository;
        public int PageSize = 5;
        public MusicController(ISongsRepository productRepository, IGenresRepository genresRepository)
        {
            this.repository = productRepository;
            this.genresRepository = genresRepository;
        }
        public ViewResult List(int? category, int page = 1)
        {
            var songs = repository.Songs
                .Where(p => category == 0 || p.GenreID == category)
                .OrderBy(p => p.ID)
                .Skip((page - 1) * PageSize)
                .Take(PageSize).ToList();
            var pagingInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = PageSize
            };
            pagingInfo.TotalItems = category == 0 ?
                repository.Songs.Count() :
                repository.Songs.Where(e => e.GenreID == category).Count();

            SongsListViewModel model = new SongsListViewModel
            {
                Songs = songs, 
                PagingInfo = pagingInfo,
                CurrentCategory = category
            };

            return View(model);
    }
        public FileContentResult GetImage(int ID)
        {
            Songs prod = repository.Songs
            .FirstOrDefault(p => p.ID == ID);
            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
        public ActionResult Details(int ID = 0)
        {
            if (ID == 0)
                throw new ArgumentNullException("Ablum is not found");

            var song = repository.Songs.SingleOrDefault(a => a.ID == ID);
            if (song == null)
                throw new ArgumentNullException("Ablum is not found");

            var model = new Songs()
            {
                ID = song.ID,
                Name = song.Name,
                Author = song.Author,
                Price = song.Price,
                GenreID = song.GenreID,
                Length = song.Length,
                ImageData = song.ImageData,
                ImageMimeType = song.ImageMimeType
            };

            return View(model);
        }

    }
}

MusicStoreWeb/Views/Admin/Edit.cshtml
@model MusicStore.Domain.Models.SongViewModel
@using MusicStoreWeb.Controllers
@{
    ViewBag.Title = "Admin: Edit " + @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="panel">
    <div class="panel-heading">
        <h3>Edit @Model.Name</h3>
    </div>
    @using (Html.BeginForm("Edit", "Admin",
     FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.ID)
            @Html.HiddenFor(m => m.ImageMimeType)
            @Html.HiddenFor(m => m.ImageData)

            @Html.ValidationSummary()
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "ID":
                    case "ImageData":
                    case "ImageMimeType":
                    case "Genres":
                  

                        // do nothing
                        break;
                    default:
                        <div class="form-group">
                            <label>@(property.DisplayName ?? property.PropertyName)</label>
                            @if (property.PropertyName == "GenreID")
                            {
                                @Html.DropDownListFor(Model => Model.GenreID, new SelectList(Model.Genres, "Value", "Text"), null, new { @class = "form-control" })

                                @*@Html.DropDownListFor(model => model.GenreID, Model.Genres, "-Select a genre-", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.GenreID, null, new { @class = "text-danger message" })*@
                            }
                            else
                            {
                                @Html.TextBox(property.PropertyName, null,
                                new { @class = "form-control" })
                            }
                            @Html.ValidationMessage(property.PropertyName)
                        </div>
                        break;
                }
            }
            <div class="form-group">
                <div style="position:relative;">
                    <label>Image</label>
                    <a class='btn'>
                        Choose File...
                        <input type="file" name="Image" size="40"
                               style="position:absolute;z-index:2;top:0; left:0;
                               filter: alpha(opacity=0); opacity:0; background-color:transparent;color:transparent;"
                               onchange='$("#upload-file-info").html($(this).val());'>
                    </a>
                    <span class='label label-info' id="upload-file-info"></span>
                </div>
                @if (Model.ImageData == null)
                {
                    <div class="form-control-static">No Image</div>

                }
                else
                {
                    <img class="img-thumbnail" width="150" height="150"
                         src="@Url.Action("GetImage", "Music", new {Model.ID})" />
                }
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and return to List", "Index", null, new
            {
            @class = "btn btn-default"
            })
        </div>
    }
</div>

MusicStoreWeb/Views/Admin/Index.cshtml
@model IEnumerable<MusicStore.Domain.Entities.Songs>
@using MusicStore.Domain.Entities;

@{
    ViewBag.Title = "Admin: All Songs";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>All Songs</h3>
        <div class="col-lg">
        <a href="/"> Bak to homepage</a>
        </div>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ID</th>
                <th>Name</th>
                <th class="text-right">Price</th>
                <th class="text-center">Actions</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">@item.ID</td>
                    <td>@Html.ActionLink(item.Name, "Edit", new { item.ID })</td>
                    <td class="text-right">@item.Price.ToString("c")</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("ID", item.ID)
                            <input type="submit"
                                   class="btn btn-default btn-xs"
                                   value="Delete" />
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Add a new song", "Create", null,
        new { @class = "btn btn-default" })

        @Html.ActionLink("Manage genres", "ListGenres", null,
        new { @class = "btn btn-default" })
    </div>
</div>

MusicStoreWeb/Views/Admin/ListGenres.cshtml
@model IEnumerable<MusicStore.Domain.Entities.Genres>

@{
    ViewBag.Title = "Admin: All Genres";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>All Genres</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ID</th>
                <th>Name</th>
            </tr>
            @foreach (var item in Model)
            {
                if (item.Name == null)
                {

                }
                else { 
                <tr>
                    <td class="text-right">@item.ID</td>
                    <td>@Html.ActionLink(item.Name, "EditG", new { item.ID })</td>

                    <td class="text-center">
                        @using (Html.BeginForm("DeleteG", "Admin"))
                        {
                            @Html.Hidden("ID", item.ID)
                            <input type="submit"
                                   class="btn btn-default btn-xs"
                                   value="Delete" />
                        }
                    </td>
                </tr>}
            }
        </table>
    </div>
    <div class="panel-footer">

        @Html.ActionLink("Add new genre", "CreateG", null,
        new { @class = "btn btn-default" })
       
        @Html.ActionLink("Return to List", "Index", null, new
{
@class = "btn btn-default"
})

    </div>
</div>

MusicStoreWeb/Views/Admin/SaveGenre.cshtml
@model MusicStore.Domain.Entities.Genres
@using MusicStore.Domain.Entities
@{
    ViewBag.Title = "Create Genre";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="panel">
    <div class="panel-heading">

    </div>
    @using (Html.BeginForm("SaveGenre", "Admin",
     FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.ID)


            @*@foreach (var property in ViewData.ModelMetadata.Properties)
        {
            switch (property.PropertyName)
            {
                case "ID":
                    break;
                default:


                    <div class="form-group">
                        <label>@(property.DisplayName ?? property.PropertyName)</label>

                        @Html.TextBox(property.PropertyName, null,
                   new { @class = "form-control" })

                        @Html.ValidationMessage(property.PropertyName)
                    </div>
                    break;


            }


        }*@
            <div class="form-group">
                <label>Name</label>

                @Html.TextBoxFor(m => m.Name, null,
           new { @class = "form-control" })
            </div>
            <div class="panel-footer">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Cancel and return to List", "ListGenres", null, new
                {
                @class = "btn btn-default"
                })
            </div>
        </div>
    }
</div >