MusicStoreWeb/Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using MusicStore.Domain.Abstract;
using MusicStore.Domain.Entities;
using MusicStore.Domain.Models;
using MusicStoreWeb.Models;

namespace MusicStoreWeb.Controllers
{
    public class CartController : Controller
    {
        private ISongsRepository repository;
        private IOrderItemRepository orderItemRepository;
        private IOrderProcessor orderProcessor;
        private IShippingDetailRepository shippingDetailRepository;
        private IOrderRepository OrderRepository;
        private IUserRepository UserRepository;
        public CartController(ISongsRepository repo, IOrderProcessor proc, IShippingDetailRepository sdetail, IOrderRepository orderRepository, IUserRepository userRepository, IOrderItemRepository orderItemRepository)
        {
            repository = repo;
            orderProcessor = proc;
            shippingDetailRepository = sdetail;
            OrderRepository = orderRepository;
            UserRepository = userRepository;
            this.orderItemRepository = orderItemRepository;
        }
        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                ReturnUrl = returnUrl,
                Cart = cart
            });
        }
        public RedirectToRouteResult AddToCart(Cart cart, int ID, string returnUrl)
        {
            Songs product = repository.Songs
            .FirstOrDefault(p => p.ID == ID);
            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }


        [HttpPost]
        public ActionResult RemoveFromCart(Cart cart, int ID, string returnUrl)
        {
            Songs product = repository.Songs
            .FirstOrDefault(p => p.ID == ID);
            if (product != null)
            {
                cart.RemoveLine(product);
            }

            CartIndexViewModel model = new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            };
            return PartialView("Recipt", model);
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        public ViewResult Checkout(Cart cart)
        {

            string value = "";

            if (Request.Cookies["fatcookie"] != null)
            {
                string value2 = Request.Cookies["fatcookie"]["username"];
                value = value2;

            }

            var user = UserRepository.User
            .Where(p => p.Username == value).FirstOrDefault();

            int ID = user.ID;


            ShippingDetail detail = shippingDetailRepository.ShippingDetail
           .LastOrDefault(p => p.ID == ID);
           

            CartIndexViewModel indexView = new CartIndexViewModel
            {
                shippingDetails = detail,
                Cart = cart
            };


            if (detail != null)
            {
                return View("FinalStep", indexView);
            }

            else
            {
                return View(new ShippingDetail());
            }
        }
        public ViewResult newShippingDetails(ShippingDetail detail)
        {
            string value = "";

            if (Request.Cookies["fatcookie"] != null)
            {
                string value2 = Request.Cookies["fatcookie"]["username"];
                value = value2;

            }

            var user = UserRepository.User
            .Where(p => p.Username == value).FirstOrDefault();

            int ID = user.ID;


            if (ModelState.IsValid)
            {


                shippingDetailRepository.SaveShippingDeatails(detail);

            }

            return View("Checkout");
            
          
        }
        public ViewResult editShipping()
        {


            string value = "";

            if (Request.Cookies["fatcookie"] != null)
            {
                string value2 = Request.Cookies["fatcookie"]["username"];
                value = value2;

            }

            var user = UserRepository.User
            .Where(p => p.Username == value).FirstOrDefault();

            string name = user.Username;


            ShippingDetail detail = shippingDetailRepository.ShippingDetail.LastOrDefault(p => p.Name== name);

            

            return View("Checkout", detail);
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetail detail)
        {


            string value = "";

            if (Request.Cookies["fatcookie"] != null)
            {
                string value2 = Request.Cookies["fatcookie"]["username"];
                value = value2;

            }


            CartIndexViewModel indexView = new CartIndexViewModel
            {
                shippingDetails = detail,
                Cart = cart
            };


            if (detail != null && ModelState.IsValid)
            {
                shippingDetailRepository.SaveShippingDeatails(detail);
                return View("FinalStep", indexView);
            }

            else
            {
                return View(new ShippingDetail());
            }


        }

        public ActionResult SaveShippingDetails(Cart cart, ShippingDetail shippingDetails)
        {
            


            string value = "";

            if (Request.Cookies["fatcookie"] != null)
            {
                string value2 = Request.Cookies["fatcookie"]["username"];
                value = value2;

            }

            var user = UserRepository.User
            .Where(p => p.Username == value).FirstOrDefault();

            int ID = user.ID;




            ShippingDetail detail = shippingDetailRepository.ShippingDetail
           .LastOrDefault(p => p.ID == ID);

            if (detail == null)
            {
                detail = shippingDetails;
            }

            CartIndexViewModel indexView = new CartIndexViewModel
            {
                shippingDetails = detail,
                Cart = cart
            };

            if (ModelState.IsValid)
            {


                shippingDetailRepository.SaveShippingDeatails(detail);

                TempData["message"] = string.Format("Shipping details with id {0} has been saved", detail.ID);
                return RedirectToAction("Index");
            }
            else
            {
                return View("FinalStep", indexView);
            }
        }



        public ActionResult Finalise(Cart cart)
        {

            

            string value = "";
            
            if (Request.Cookies["fatcookie"] != null)
            {
                string value2 = Request.Cookies["fatcookie"]["username"];
                value = value2;

            }


            var user = UserRepository.User
            .Where(p => p.Username == value).FirstOrDefault();

            var shiping = shippingDetailRepository.ShippingDetail.Where(p => p.Name == value).LastOrDefault();
            int SID = shiping.ID;

            int UID = user.ID;

            CartViewModel model = new CartViewModel
            {
                Cart = cart,
                shippingDetails = shiping

            };

          
            OrderRepository.CreateNewOrder(SID, UID, model);

            Order neworder = OrderRepository.Order.LastOrDefault(p => p.UserID == UID);

            orderItemRepository.AddOrder(neworder.ID, model);

            

            return View("Finalised");
        }
        public ActionResult detailExists(Cart cart)
        {
            string value = "";

            if (Request.Cookies["fatcookie"] != null)
            {
                string value2 = Request.Cookies["fatcookie"]["username"];
                value = value2;

            }

            var userd = shippingDetailRepository.ShippingDetail.Where(m => m.Name == value).FirstOrDefault(); ;

            CartIndexViewModel indexView = new CartIndexViewModel
            {
                shippingDetails = userd,
                Cart = cart
            };

            var s = cart.Lines.FirstOrDefault();


            if (s == null)
            {
                return RedirectToAction("Index");
            }
            else { 
            if (userd== null)
            {
                return RedirectToAction("newShippingDetails", new ShippingDetail());
              
            }
            else
            {

                return View("FinalStep", indexView);
            }
            }


        }

        public ActionResult OrderSongs(Cart cart)
        {


            return View();
        }

    }
}

MusicStoreWeb/Controllers/MusicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicStore.Domain.Abstract;
using MusicStore.Domain.Entities;
using MusicStoreWeb.Models;

namespace SportsStore.WebUI.Controllers
{
    public class MusicController : Controller
    {
        private ISongsRepository repository;
        private IGenresRepository genresRepository;
        public int PageSize = 5;
        public MusicController(ISongsRepository productRepository, IGenresRepository genresRepository)
        {
            this.repository = productRepository;
            this.genresRepository = genresRepository;
        }
        public ViewResult List(int? category, int page = 1)
        {
            var songs = repository.Songs
                .Where(p => category == 0 || p.GenreID == category)
                .OrderBy(p => p.ID)
                .Skip((page - 1) * PageSize)
                .Take(PageSize).ToList();
            var pagingInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = PageSize
            };
            pagingInfo.TotalItems = category == 0 ?
                repository.Songs.Count() :
                repository.Songs.Where(e => e.GenreID == category).Count();

            SongsListViewModel model = new SongsListViewModel
            {
                Songs = songs, 
                PagingInfo = pagingInfo,
                CurrentCategory = category
            };

            return View(model);
    }
        public FileContentResult GetImage(int ID)
        {
            Songs prod = repository.Songs
            .FirstOrDefault(p => p.ID == ID);
            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
        public ActionResult Details(int ID = 0)
        {
            if (ID == 0)
                throw new ArgumentNullException("Ablum is not found");

            var song = repository.Songs.SingleOrDefault(a => a.ID == ID);
            if (song == null)
                throw new ArgumentNullException("Ablum is not found");

            var model = new Songs()
            {
                ID = song.ID,
                Name = song.Name,
                Author = song.Author,
                Price = song.Price,
                GenreID = song.GenreID,
                Length = song.Length,
                ImageData = song.ImageData,
                ImageMimeType = song.ImageMimeType
            };

            return View(model);
        }

    }
}

MusicStoreWeb/Views/Cart/Checkout.cshtml
@model MusicStore.Domain.Entities.ShippingDetail
@using MusicStore.Domain.Entities;
@{
    ViewBag.Title = "Checkout";
}
<h2>Check out now</h2>
<p>Please enter your details, and we'll ship your goods right away!</p>

@using (Html.BeginForm("SaveShippingDetails", "Cart"))
{

    @Html.ValidationSummary()
    <h3>Ship to</h3>
    <div class="form-group">
        <label>Name:</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    </div>
    <h3>Address</h3>
    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "Name" && property.PropertyName != "GiftWrap" && property.PropertyName != "Orders")
        {
            <div class="form-group">
                <label>@(property.DisplayName ?? property.PropertyName)</label>
                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
            </div>
        }
    }
    <h3>Options</h3>
    <div class="checkbox">
        <label>
            @Html.EditorFor(x => x.GiftWrap)
            Gift wrap these items
        </label>
    </div>
    <div class="text-center">
        @Html.ActionLink("Save shipping details", "SaveShippingDetails", null,
        new { @class = "btn btn-default" })
    </div>
}

MusicStoreWeb/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = " Order Submitted ";
}
<h2>Thanks!</h2>
Thanks for placing your order. You should get access to the songs in  just a moment!

MusicStoreWeb/Views/Cart/FinalStep.cshtml
@model MusicStoreWeb.Models.CartIndexViewModel

<h2>Final steps!</h2>


@Html.ActionLink("Edit shipping details", "editShipping", null, new
            {
            @class = "btn btn-default"
            })

<h2>Reciept</h2>
<table id="cartTable" class="table">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Item</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Product.Name</td>
                <td class="text-right">@line.Product.Price.ToString("c")</td>
                <td class="text-right">
                    @((line.Quantity * line.Product.Price).ToString("c"))
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    @Html.ActionLink("Complete order", "Finalise", null, new { @class = "btn btn-primary" })
</div>

MusicStoreWeb/Views/Cart/Finalised.cshtml
@{
    ViewBag.Title = " Order Submitted ";
}
<h2>Thanks!</h2>
Thanks for placing your order. You should get access to the songs in  just a moment!

MusicStoreWeb/Views/Cart/Index.cshtml
@model MusicStoreWeb.Models.CartIndexViewModel
@{
    ViewBag.Title = "Music Store: Your Cart";


}
<style>
    #cartTable td {
        vertical-align: middle;
    }
</style>



<h2>Your cart</h2>
<div id="Info">

    @Html.Partial("~/Views/Cart/Recipt.cshtml", Model)

</div>

<div class="text-center">
    @Html.ActionLink("Home", "List", "Music", null, new { @class = "btn btn-primary" })

    @Html.ActionLink("Checkout now", "detailExists", null, new { @class = "btn btn-primary" })
</div>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script src="~/Scripts/jquery-3.6.1.min.js"></script>

MusicStoreWeb/Views/Cart/Recipt.cshtml
@model MusicStoreWeb.Models.CartIndexViewModel


@{
    AjaxOptions ajaxOptions = new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "Info"
    };

}
    <table id="cartTable" class="table">
        <thead>
            <tr>
                <th>Quantity</th>
                <th>Item</th>
                <th class="text-right">Price</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.Cart.Lines)
            {
                <tr>
                    <td class="text-center">@line.Quantity</td>
                    <td class="text-left">@line.Product.Name</td>
                    <td class="text-right">@line.Product.Price.ToString("c")</td>
                    <td class="text-right">
                        @((line.Quantity * line.Product.Price).ToString("c"))
                    </td>
                    <td class="text-right">
                        @using (Ajax.BeginForm("RemoveFromCart", "Cart", ajaxOptions))
                        {
                            @Html.Hidden("ID", line.Product.ID)
                            @Html.HiddenFor(x => x.ReturnUrl)
                            <input class="btn btn-sm btn-warning"
                                   type="submit"  id="SubmitButton" value="Remove" />

                        }
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                    @Model.Cart.ComputeTotalValue().ToString("c")
                </td>
            </tr>
        </tfoot>
    </table>




<script src="~/Scripts/jquery-3.6.1.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

MusicStoreWeb/Views/Cart/Summary.cshtml
@model MusicStore.Domain.Entities.Cart
<div class="navbar-right hidden-xs">
    @Html.ActionLink("Checkout", "Index", "Cart",
    new { returnUrl = Request.Url.PathAndQuery },
    new { @class = "btn btn-default navbar-btn" })
</div>
<div class="navbar-right visible-xs">
    <a href=@Url.Action("Index", "Cart", new { returnUrl = Request.Url.PathAndQuery })
       class="btn btn-default navbar-btn">
        <span class="glyphicon glyphicon-shopping-cart"></span>
    </a>
</div>
<div class="navbar-text navbar-right">
    <b class="hidden-xs">Your cart:</b>
    @Model.Lines.Sum(x => x.Quantity) item(s),
    @Model.ComputeTotalValue().ToString("c")
</div>

MusicStoreWeb/Views/Cart/newShippingDetails.cshtml
@model MusicStore.Domain.Entities.ShippingDetail
@using MusicStore.Domain.Entities;

<h2>Check out now</h2>
<p>Please enter your details, and we'll ship your goods right away!</p>


@using (Html.BeginForm("newShippingDetails", "Cart", FormMethod.Post))
{
    string value = "";

    if (Request.Cookies["fatcookie"] != null)
    {
        string value2 = Request.Cookies["fatcookie"]["username"];
        value = value2;

    }


    <h3>Ship to</h3>
    <div class="form-group">
        <label>Name:</label>

        @value
    </div>

    <h3>Address</h3>


    <div class="form-group">
        <label>Line1</label>
        @Html.TextBoxFor(model => model.Name, new { @Value = value, @type = "hidden" })
    </div>


    <div class="form-group">
        <label>Line1</label>
        @Html.TextBoxFor(model => model.Line1, null, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Line2</label>
        @Html.TextBoxFor(model => model.Line2, null, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Line3</label>
        @Html.TextBoxFor(model => model.Line3, null, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>City</label>
        @Html.TextBoxFor(model => model.City, null, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>State</label>
        @Html.TextBoxFor(model => model.State, null, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>zip</label>
        @Html.TextBoxFor(model => model.Zip, null, new { @class = "form-control" })
    </div> <div class="form-group">
        <label>Country</label>
        @Html.TextBoxFor(model => model.Country, null, new { @class = "form-control" })
    </div>



    <h3>Options</h3>
    <div class="checkbox">
        <label>
            @Html.EditorFor(x => x.GiftWrap)
            Gift wrap these items
        </label>
    </div>

    <div class="text-center">

        <a href="/">
            <input class="btn btn-primary" type="submit" value="Complete order" />
        </a>
    </div>


}